### ISSUE TITLE
IDs for definitions

### ISSUE THREAD

**Issue by wederbn** [OpenTOSCA/tosca-normative-types#1]
Currently the IDs for definitions are defined as "winery-defs-for_$NAMESPACE-$NAME" (e.g., "winery-defs-for_ToscaNormativeNodeTypes-BlockStorage", see [here](https://github.com/OpenTOSCA/tosca-normative-types/blob/main/nodetypes/http%253A%252F%252Fdocs.oasis-open.org%252Ftosca%252FToscaNormativeTypes%252Fnodetypes/BlockStorage/NodeType.tosca)).

Maybe the "winery-defs-for" should be removed and only namespace + name used as unique IDs.

**Comment by lharzenetter** [comment]
should be fixed by https://github.com/eclipse/winery/pull/600
